/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uoc.som.tracea.ide.contentassist.antlr.internal.InternalTraceaParser;
import uoc.som.tracea.services.TraceaGrammarAccess;

public class TraceaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TraceaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TraceaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTrustableElementAccess().getAlternatives(), "rule__TrustableElement__Alternatives");
			builder.put(grammarAccess.getTraceAccess().getAlternatives_6(), "rule__Trace__Alternatives_6");
			builder.put(grammarAccess.getTraceLinkAccess().getAlternatives(), "rule__TraceLink__Alternatives");
			builder.put(grammarAccess.getArtefactAccess().getAlternatives(), "rule__Artefact__Alternatives");
			builder.put(grammarAccess.getModelArtefactAccess().getAlternatives(), "rule__ModelArtefact__Alternatives");
			builder.put(grammarAccess.getTextArtefactAccess().getAlternatives(), "rule__TextArtefact__Alternatives");
			builder.put(grammarAccess.getArtefactFragmentAccess().getAlternatives(), "rule__ArtefactFragment__Alternatives");
			builder.put(grammarAccess.getTextFragmentAccess().getAlternatives(), "rule__TextFragment__Alternatives");
			builder.put(grammarAccess.getModelFragmentAccess().getAlternatives(), "rule__ModelFragment__Alternatives");
			builder.put(grammarAccess.getRelationshipTypeAccess().getAlternatives(), "rule__RelationshipType__Alternatives");
			builder.put(grammarAccess.getEvidenceAccess().getAlternatives(), "rule__Evidence__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getTraceaAccess().getGroup(), "rule__Tracea__Group__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_4(), "rule__Tracea__Group_4__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_4_3(), "rule__Tracea__Group_4_3__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_5(), "rule__Tracea__Group_5__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_5_3(), "rule__Tracea__Group_5_3__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_6(), "rule__Tracea__Group_6__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_6_3(), "rule__Tracea__Group_6_3__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_7(), "rule__Tracea__Group_7__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_7_3(), "rule__Tracea__Group_7_3__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_8(), "rule__Tracea__Group_8__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_8_3(), "rule__Tracea__Group_8_3__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_9(), "rule__Tracea__Group_9__0");
			builder.put(grammarAccess.getTraceaAccess().getGroup_9_3(), "rule__Tracea__Group_9_3__0");
			builder.put(grammarAccess.getTraceAccess().getGroup(), "rule__Trace__Group__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_4(), "rule__Trace__Group_4__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_5(), "rule__Trace__Group_5__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_5_3(), "rule__Trace__Group_5_3__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_6_0(), "rule__Trace__Group_6_0__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_6_1(), "rule__Trace__Group_6_1__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_6_1_0(), "rule__Trace__Group_6_1_0__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_7(), "rule__Trace__Group_7__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_7_3(), "rule__Trace__Group_7_3__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_8(), "rule__Trace__Group_8__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_8_3(), "rule__Trace__Group_8_3__0");
			builder.put(grammarAccess.getTraceAccess().getGroup_9(), "rule__Trace__Group_9__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup(), "rule__LeafTraceLink__Group__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_4(), "rule__LeafTraceLink__Group_4__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_5(), "rule__LeafTraceLink__Group_5__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_6(), "rule__LeafTraceLink__Group_6__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_7(), "rule__LeafTraceLink__Group_7__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_7_3(), "rule__LeafTraceLink__Group_7_3__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_8(), "rule__LeafTraceLink__Group_8__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_8_3(), "rule__LeafTraceLink__Group_8_3__0");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getGroup_9(), "rule__LeafTraceLink__Group_9__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup(), "rule__NodeTraceLink__Group__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_4(), "rule__NodeTraceLink__Group_4__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_5(), "rule__NodeTraceLink__Group_5__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_6(), "rule__NodeTraceLink__Group_6__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_6_3(), "rule__NodeTraceLink__Group_6_3__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_7(), "rule__NodeTraceLink__Group_7__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_8(), "rule__NodeTraceLink__Group_8__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_8_3(), "rule__NodeTraceLink__Group_8_3__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_9(), "rule__NodeTraceLink__Group_9__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_9_3(), "rule__NodeTraceLink__Group_9_3__0");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getGroup_10(), "rule__NodeTraceLink__Group_10__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup(), "rule__ModelArtefact_Impl__Group__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup_4(), "rule__ModelArtefact_Impl__Group_4__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup_4_3(), "rule__ModelArtefact_Impl__Group_4_3__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup_5(), "rule__ModelArtefact_Impl__Group_5__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup_5_3(), "rule__ModelArtefact_Impl__Group_5_3__0");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getGroup_6(), "rule__ModelArtefact_Impl__Group_6__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup(), "rule__TextArtefact_Impl__Group__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup_4(), "rule__TextArtefact_Impl__Group_4__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup_4_3(), "rule__TextArtefact_Impl__Group_4_3__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup_5(), "rule__TextArtefact_Impl__Group_5__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup_6(), "rule__TextArtefact_Impl__Group_6__0");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getGroup_6_3(), "rule__TextArtefact_Impl__Group_6_3__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup(), "rule__TextFragment_Impl__Group__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup_4(), "rule__TextFragment_Impl__Group_4__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup_4_3(), "rule__TextFragment_Impl__Group_4_3__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup_5(), "rule__TextFragment_Impl__Group_5__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup_5_3(), "rule__TextFragment_Impl__Group_5_3__0");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getGroup_6(), "rule__TextFragment_Impl__Group_6__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_4(), "rule__Document__Group_4__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_5(), "rule__Document__Group_5__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_5_3(), "rule__Document__Group_5_3__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_6(), "rule__Document__Group_6__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_6_3(), "rule__Document__Group_6_3__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_7(), "rule__Document__Group_7__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_7_3(), "rule__Document__Group_7_3__0");
			builder.put(grammarAccess.getDocumentAccess().getGroup_8(), "rule__Document__Group_8__0");
			builder.put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_5_3(), "rule__Section__Group_5_3__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_6_3(), "rule__Section__Group_6_3__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_7(), "rule__Section__Group_7__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_7_3(), "rule__Section__Group_7_3__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_8(), "rule__Section__Group_8__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_8_3(), "rule__Section__Group_8_3__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_9(), "rule__Section__Group_9__0");
			builder.put(grammarAccess.getPartOfSpeechAccess().getGroup(), "rule__PartOfSpeech__Group__0");
			builder.put(grammarAccess.getPartOfSpeechAccess().getGroup_4(), "rule__PartOfSpeech__Group_4__0");
			builder.put(grammarAccess.getPartOfSpeechAccess().getGroup_5(), "rule__PartOfSpeech__Group_5__0");
			builder.put(grammarAccess.getPartOfSpeechAccess().getGroup_5_3(), "rule__PartOfSpeech__Group_5_3__0");
			builder.put(grammarAccess.getPartOfSpeechAccess().getGroup_6(), "rule__PartOfSpeech__Group_6__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup(), "rule__ModelFragment_Impl__Group__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_4(), "rule__ModelFragment_Impl__Group_4__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_4_3(), "rule__ModelFragment_Impl__Group_4_3__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_5(), "rule__ModelFragment_Impl__Group_5__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_5_3(), "rule__ModelFragment_Impl__Group_5_3__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_6(), "rule__ModelFragment_Impl__Group_6__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_6_3(), "rule__ModelFragment_Impl__Group_6_3__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_7(), "rule__ModelFragment_Impl__Group_7__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_7_3(), "rule__ModelFragment_Impl__Group_7_3__0");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getGroup_8(), "rule__ModelFragment_Impl__Group_8__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4_3(), "rule__Model__Group_4_3__0");
			builder.put(grammarAccess.getModelAccess().getGroup_5(), "rule__Model__Group_5__0");
			builder.put(grammarAccess.getModelAccess().getGroup_5_3(), "rule__Model__Group_5_3__0");
			builder.put(grammarAccess.getModelAccess().getGroup_6(), "rule__Model__Group_6__0");
			builder.put(grammarAccess.getModelAccess().getGroup_6_3(), "rule__Model__Group_6_3__0");
			builder.put(grammarAccess.getModelAccess().getGroup_7(), "rule__Model__Group_7__0");
			builder.put(grammarAccess.getNamedElementAccess().getGroup(), "rule__NamedElement__Group__0");
			builder.put(grammarAccess.getNamedElementAccess().getGroup_4(), "rule__NamedElement__Group_4__0");
			builder.put(grammarAccess.getNamedElementAccess().getGroup_4_3(), "rule__NamedElement__Group_4_3__0");
			builder.put(grammarAccess.getNamedElementAccess().getGroup_5(), "rule__NamedElement__Group_5__0");
			builder.put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_4(), "rule__Package__Group_4__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_4_3(), "rule__Package__Group_4_3__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_5(), "rule__Package__Group_5__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_5_3(), "rule__Package__Group_5_3__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_6(), "rule__Package__Group_6__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_6_3(), "rule__Package__Group_6_3__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_7(), "rule__Package__Group_7__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_7_3(), "rule__Package__Group_7_3__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_8(), "rule__Package__Group_8__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_8_3(), "rule__Package__Group_8_3__0");
			builder.put(grammarAccess.getPackageAccess().getGroup_9(), "rule__Package__Group_9__0");
			builder.put(grammarAccess.getClasseAccess().getGroup(), "rule__Classe__Group__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_4(), "rule__Classe__Group_4__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_4_3(), "rule__Classe__Group_4_3__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_5(), "rule__Classe__Group_5__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_5_3(), "rule__Classe__Group_5_3__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_6(), "rule__Classe__Group_6__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_6_3(), "rule__Classe__Group_6_3__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_7(), "rule__Classe__Group_7__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_7_3(), "rule__Classe__Group_7_3__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_8(), "rule__Classe__Group_8__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_8_3(), "rule__Classe__Group_8_3__0");
			builder.put(grammarAccess.getClasseAccess().getGroup_9(), "rule__Classe__Group_9__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup(), "rule__StructuralFeature__Group__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_4(), "rule__StructuralFeature__Group_4__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_4_3(), "rule__StructuralFeature__Group_4_3__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_5(), "rule__StructuralFeature__Group_5__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_5_3(), "rule__StructuralFeature__Group_5_3__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_6(), "rule__StructuralFeature__Group_6__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_6_3(), "rule__StructuralFeature__Group_6_3__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_7(), "rule__StructuralFeature__Group_7__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_7_3(), "rule__StructuralFeature__Group_7_3__0");
			builder.put(grammarAccess.getStructuralFeatureAccess().getGroup_8(), "rule__StructuralFeature__Group_8__0");
			builder.put(grammarAccess.getDomainType_ImplAccess().getGroup(), "rule__DomainType_Impl__Group__0");
			builder.put(grammarAccess.getEngineeringType_ImplAccess().getGroup(), "rule__EngineeringType_Impl__Group__0");
			builder.put(grammarAccess.getTransclusionAccess().getGroup(), "rule__Transclusion__Group__0");
			builder.put(grammarAccess.getDoc2SectionAccess().getGroup(), "rule__Doc2Section__Group__0");
			builder.put(grammarAccess.getSection2PoSAccess().getGroup(), "rule__Section2PoS__Group__0");
			builder.put(grammarAccess.getPoSSynonymAccess().getGroup(), "rule__PoSSynonym__Group__0");
			builder.put(grammarAccess.getPoS2NamedEntityAccess().getGroup(), "rule__PoS2NamedEntity__Group__0");
			builder.put(grammarAccess.getNamedEntitySynonymAccess().getGroup(), "rule__NamedEntitySynonym__Group__0");
			builder.put(grammarAccess.getNamedEntity2ClassAccess().getGroup(), "rule__NamedEntity2Class__Group__0");
			builder.put(grammarAccess.getNameEntity2PackageAccess().getGroup(), "rule__NameEntity2Package__Group__0");
			builder.put(grammarAccess.getPackage2ModelAccess().getGroup(), "rule__Package2Model__Group__0");
			builder.put(grammarAccess.getRefereeAccess().getGroup(), "rule__Referee__Group__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup(), "rule__Evidence_Impl__Group__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup_4(), "rule__Evidence_Impl__Group_4__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup_4_3(), "rule__Evidence_Impl__Group_4_3__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup_5(), "rule__Evidence_Impl__Group_5__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup_5_3(), "rule__Evidence_Impl__Group_5_3__0");
			builder.put(grammarAccess.getEvidence_ImplAccess().getGroup_6(), "rule__Evidence_Impl__Group_6__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup(), "rule__RuleEvidence__Group__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_4(), "rule__RuleEvidence__Group_4__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_5(), "rule__RuleEvidence__Group_5__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_6(), "rule__RuleEvidence__Group_6__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_6_3(), "rule__RuleEvidence__Group_6_3__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_7(), "rule__RuleEvidence__Group_7__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_7_3(), "rule__RuleEvidence__Group_7_3__0");
			builder.put(grammarAccess.getRuleEvidenceAccess().getGroup_8(), "rule__RuleEvidence__Group_8__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup(), "rule__AnnotationEvidence__Group__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_4(), "rule__AnnotationEvidence__Group_4__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_5(), "rule__AnnotationEvidence__Group_5__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_5_3(), "rule__AnnotationEvidence__Group_5_3__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_6(), "rule__AnnotationEvidence__Group_6__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_6_3(), "rule__AnnotationEvidence__Group_6_3__0");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getGroup_7(), "rule__AnnotationEvidence__Group_7__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup(), "rule__AIEvidence__Group__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_4(), "rule__AIEvidence__Group_4__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_5(), "rule__AIEvidence__Group_5__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_5_3(), "rule__AIEvidence__Group_5_3__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_6(), "rule__AIEvidence__Group_6__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_7(), "rule__AIEvidence__Group_7__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_8(), "rule__AIEvidence__Group_8__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_8_3(), "rule__AIEvidence__Group_8_3__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_9(), "rule__AIEvidence__Group_9__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_9_3(), "rule__AIEvidence__Group_9_3__0");
			builder.put(grammarAccess.getAIEvidenceAccess().getGroup_10(), "rule__AIEvidence__Group_10__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getTraceaAccess().getNameAssignment_2(), "rule__Tracea__NameAssignment_2");
			builder.put(grammarAccess.getTraceaAccess().getTracesAssignment_4_2(), "rule__Tracea__TracesAssignment_4_2");
			builder.put(grammarAccess.getTraceaAccess().getTracesAssignment_4_3_1(), "rule__Tracea__TracesAssignment_4_3_1");
			builder.put(grammarAccess.getTraceaAccess().getRelationshiptypesAssignment_5_2(), "rule__Tracea__RelationshiptypesAssignment_5_2");
			builder.put(grammarAccess.getTraceaAccess().getRelationshiptypesAssignment_5_3_1(), "rule__Tracea__RelationshiptypesAssignment_5_3_1");
			builder.put(grammarAccess.getTraceaAccess().getArtefactsAssignment_6_2(), "rule__Tracea__ArtefactsAssignment_6_2");
			builder.put(grammarAccess.getTraceaAccess().getArtefactsAssignment_6_3_1(), "rule__Tracea__ArtefactsAssignment_6_3_1");
			builder.put(grammarAccess.getTraceaAccess().getFragmentsAssignment_7_2(), "rule__Tracea__FragmentsAssignment_7_2");
			builder.put(grammarAccess.getTraceaAccess().getFragmentsAssignment_7_3_1(), "rule__Tracea__FragmentsAssignment_7_3_1");
			builder.put(grammarAccess.getTraceaAccess().getEvidencesAssignment_8_2(), "rule__Tracea__EvidencesAssignment_8_2");
			builder.put(grammarAccess.getTraceaAccess().getEvidencesAssignment_8_3_1(), "rule__Tracea__EvidencesAssignment_8_3_1");
			builder.put(grammarAccess.getTraceaAccess().getRefereesAssignment_9_2(), "rule__Tracea__RefereesAssignment_9_2");
			builder.put(grammarAccess.getTraceaAccess().getRefereesAssignment_9_3_1(), "rule__Tracea__RefereesAssignment_9_3_1");
			builder.put(grammarAccess.getTraceAccess().getNameAssignment_2(), "rule__Trace__NameAssignment_2");
			builder.put(grammarAccess.getTraceAccess().getRelationshiptypeAssignment_4_1(), "rule__Trace__RelationshiptypeAssignment_4_1");
			builder.put(grammarAccess.getTraceAccess().getEvidencesAssignment_5_2(), "rule__Trace__EvidencesAssignment_5_2");
			builder.put(grammarAccess.getTraceAccess().getEvidencesAssignment_5_3_1(), "rule__Trace__EvidencesAssignment_5_3_1");
			builder.put(grammarAccess.getTraceAccess().getStartsAssignment_6_0_2(), "rule__Trace__StartsAssignment_6_0_2");
			builder.put(grammarAccess.getTraceAccess().getStartsAssignment_6_1_0_1(), "rule__Trace__StartsAssignment_6_1_0_1");
			builder.put(grammarAccess.getTraceAccess().getTracelinksAssignment_7_2(), "rule__Trace__TracelinksAssignment_7_2");
			builder.put(grammarAccess.getTraceAccess().getTracelinksAssignment_7_3_1(), "rule__Trace__TracelinksAssignment_7_3_1");
			builder.put(grammarAccess.getTraceAccess().getRefereesAssignment_8_2(), "rule__Trace__RefereesAssignment_8_2");
			builder.put(grammarAccess.getTraceAccess().getRefereesAssignment_8_3_1(), "rule__Trace__RefereesAssignment_8_3_1");
			builder.put(grammarAccess.getTraceAccess().getTimestampAssignment_9_1(), "rule__Trace__TimestampAssignment_9_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getNameAssignment_2(), "rule__LeafTraceLink__NameAssignment_2");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getSourceAssignment_4_1(), "rule__LeafTraceLink__SourceAssignment_4_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getTargetAssignment_5_1(), "rule__LeafTraceLink__TargetAssignment_5_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getRelationshiptypeAssignment_6_1(), "rule__LeafTraceLink__RelationshiptypeAssignment_6_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getEvidencesAssignment_7_2(), "rule__LeafTraceLink__EvidencesAssignment_7_2");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getEvidencesAssignment_7_3_1(), "rule__LeafTraceLink__EvidencesAssignment_7_3_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getRefereesAssignment_8_2(), "rule__LeafTraceLink__RefereesAssignment_8_2");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getRefereesAssignment_8_3_1(), "rule__LeafTraceLink__RefereesAssignment_8_3_1");
			builder.put(grammarAccess.getLeafTraceLinkAccess().getTimestampAssignment_9_1(), "rule__LeafTraceLink__TimestampAssignment_9_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getNameAssignment_2(), "rule__NodeTraceLink__NameAssignment_2");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getSourceAssignment_4_1(), "rule__NodeTraceLink__SourceAssignment_4_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getTargetAssignment_5_1(), "rule__NodeTraceLink__TargetAssignment_5_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getSuccessorsAssignment_6_2(), "rule__NodeTraceLink__SuccessorsAssignment_6_2");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getSuccessorsAssignment_6_3_1(), "rule__NodeTraceLink__SuccessorsAssignment_6_3_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getRelationshiptypeAssignment_7_1(), "rule__NodeTraceLink__RelationshiptypeAssignment_7_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getEvidencesAssignment_8_2(), "rule__NodeTraceLink__EvidencesAssignment_8_2");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getEvidencesAssignment_8_3_1(), "rule__NodeTraceLink__EvidencesAssignment_8_3_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getRefereesAssignment_9_2(), "rule__NodeTraceLink__RefereesAssignment_9_2");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getRefereesAssignment_9_3_1(), "rule__NodeTraceLink__RefereesAssignment_9_3_1");
			builder.put(grammarAccess.getNodeTraceLinkAccess().getTimestampAssignment_10_1(), "rule__NodeTraceLink__TimestampAssignment_10_1");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getNameAssignment_2(), "rule__ModelArtefact_Impl__NameAssignment_2");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getFragmentsAssignment_4_2(), "rule__ModelArtefact_Impl__FragmentsAssignment_4_2");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getFragmentsAssignment_4_3_1(), "rule__ModelArtefact_Impl__FragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getRefereesAssignment_5_2(), "rule__ModelArtefact_Impl__RefereesAssignment_5_2");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getRefereesAssignment_5_3_1(), "rule__ModelArtefact_Impl__RefereesAssignment_5_3_1");
			builder.put(grammarAccess.getModelArtefact_ImplAccess().getTimestampAssignment_6_1(), "rule__ModelArtefact_Impl__TimestampAssignment_6_1");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getNameAssignment_2(), "rule__TextArtefact_Impl__NameAssignment_2");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getFragmentsAssignment_4_2(), "rule__TextArtefact_Impl__FragmentsAssignment_4_2");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getFragmentsAssignment_4_3_1(), "rule__TextArtefact_Impl__FragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getTimestampAssignment_5_1(), "rule__TextArtefact_Impl__TimestampAssignment_5_1");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getRefereesAssignment_6_2(), "rule__TextArtefact_Impl__RefereesAssignment_6_2");
			builder.put(grammarAccess.getTextArtefact_ImplAccess().getRefereesAssignment_6_3_1(), "rule__TextArtefact_Impl__RefereesAssignment_6_3_1");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getNameAssignment_2(), "rule__TextFragment_Impl__NameAssignment_2");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getSubFragmentsAssignment_4_2(), "rule__TextFragment_Impl__SubFragmentsAssignment_4_2");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getSubFragmentsAssignment_4_3_1(), "rule__TextFragment_Impl__SubFragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getRefereesAssignment_5_2(), "rule__TextFragment_Impl__RefereesAssignment_5_2");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getRefereesAssignment_5_3_1(), "rule__TextFragment_Impl__RefereesAssignment_5_3_1");
			builder.put(grammarAccess.getTextFragment_ImplAccess().getTimestampAssignment_6_1(), "rule__TextFragment_Impl__TimestampAssignment_6_1");
			builder.put(grammarAccess.getDocumentAccess().getNameAssignment_2(), "rule__Document__NameAssignment_2");
			builder.put(grammarAccess.getDocumentAccess().getTitleAssignment_4_1(), "rule__Document__TitleAssignment_4_1");
			builder.put(grammarAccess.getDocumentAccess().getFragmentsAssignment_5_2(), "rule__Document__FragmentsAssignment_5_2");
			builder.put(grammarAccess.getDocumentAccess().getFragmentsAssignment_5_3_1(), "rule__Document__FragmentsAssignment_5_3_1");
			builder.put(grammarAccess.getDocumentAccess().getSectionsAssignment_6_2(), "rule__Document__SectionsAssignment_6_2");
			builder.put(grammarAccess.getDocumentAccess().getSectionsAssignment_6_3_1(), "rule__Document__SectionsAssignment_6_3_1");
			builder.put(grammarAccess.getDocumentAccess().getRefereesAssignment_7_2(), "rule__Document__RefereesAssignment_7_2");
			builder.put(grammarAccess.getDocumentAccess().getRefereesAssignment_7_3_1(), "rule__Document__RefereesAssignment_7_3_1");
			builder.put(grammarAccess.getDocumentAccess().getTimestampAssignment_8_1(), "rule__Document__TimestampAssignment_8_1");
			builder.put(grammarAccess.getSectionAccess().getNameAssignment_2(), "rule__Section__NameAssignment_2");
			builder.put(grammarAccess.getSectionAccess().getNumberAssignment_4_1(), "rule__Section__NumberAssignment_4_1");
			builder.put(grammarAccess.getSectionAccess().getSubFragmentsAssignment_5_2(), "rule__Section__SubFragmentsAssignment_5_2");
			builder.put(grammarAccess.getSectionAccess().getSubFragmentsAssignment_5_3_1(), "rule__Section__SubFragmentsAssignment_5_3_1");
			builder.put(grammarAccess.getSectionAccess().getPartofspeechsDefinedAssignment_6_2(), "rule__Section__PartofspeechsDefinedAssignment_6_2");
			builder.put(grammarAccess.getSectionAccess().getPartofspeechsDefinedAssignment_6_3_1(), "rule__Section__PartofspeechsDefinedAssignment_6_3_1");
			builder.put(grammarAccess.getSectionAccess().getPartofspeechsUsedAssignment_7_2(), "rule__Section__PartofspeechsUsedAssignment_7_2");
			builder.put(grammarAccess.getSectionAccess().getPartofspeechsUsedAssignment_7_3_1(), "rule__Section__PartofspeechsUsedAssignment_7_3_1");
			builder.put(grammarAccess.getSectionAccess().getRefereesAssignment_8_2(), "rule__Section__RefereesAssignment_8_2");
			builder.put(grammarAccess.getSectionAccess().getRefereesAssignment_8_3_1(), "rule__Section__RefereesAssignment_8_3_1");
			builder.put(grammarAccess.getSectionAccess().getTimestampAssignment_9_1(), "rule__Section__TimestampAssignment_9_1");
			builder.put(grammarAccess.getPartOfSpeechAccess().getNameAssignment_2(), "rule__PartOfSpeech__NameAssignment_2");
			builder.put(grammarAccess.getPartOfSpeechAccess().getPositionAssignment_4_1(), "rule__PartOfSpeech__PositionAssignment_4_1");
			builder.put(grammarAccess.getPartOfSpeechAccess().getRefereesAssignment_5_2(), "rule__PartOfSpeech__RefereesAssignment_5_2");
			builder.put(grammarAccess.getPartOfSpeechAccess().getRefereesAssignment_5_3_1(), "rule__PartOfSpeech__RefereesAssignment_5_3_1");
			builder.put(grammarAccess.getPartOfSpeechAccess().getTimestampAssignment_6_1(), "rule__PartOfSpeech__TimestampAssignment_6_1");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getNameAssignment_2(), "rule__ModelFragment_Impl__NameAssignment_2");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getSubFragmentsAssignment_4_2(), "rule__ModelFragment_Impl__SubFragmentsAssignment_4_2");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getSubFragmentsAssignment_4_3_1(), "rule__ModelFragment_Impl__SubFragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getNamedelementsDefinedAssignment_5_2(), "rule__ModelFragment_Impl__NamedelementsDefinedAssignment_5_2");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getNamedelementsDefinedAssignment_5_3_1(), "rule__ModelFragment_Impl__NamedelementsDefinedAssignment_5_3_1");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getNamedelementsUsedAssignment_6_2(), "rule__ModelFragment_Impl__NamedelementsUsedAssignment_6_2");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getNamedelementsUsedAssignment_6_3_1(), "rule__ModelFragment_Impl__NamedelementsUsedAssignment_6_3_1");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getRefereesAssignment_7_2(), "rule__ModelFragment_Impl__RefereesAssignment_7_2");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getRefereesAssignment_7_3_1(), "rule__ModelFragment_Impl__RefereesAssignment_7_3_1");
			builder.put(grammarAccess.getModelFragment_ImplAccess().getTimestampAssignment_8_1(), "rule__ModelFragment_Impl__TimestampAssignment_8_1");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
			builder.put(grammarAccess.getModelAccess().getFragmentsAssignment_4_2(), "rule__Model__FragmentsAssignment_4_2");
			builder.put(grammarAccess.getModelAccess().getFragmentsAssignment_4_3_1(), "rule__Model__FragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getModelAccess().getPackagesAssignment_5_2(), "rule__Model__PackagesAssignment_5_2");
			builder.put(grammarAccess.getModelAccess().getPackagesAssignment_5_3_1(), "rule__Model__PackagesAssignment_5_3_1");
			builder.put(grammarAccess.getModelAccess().getRefereesAssignment_6_2(), "rule__Model__RefereesAssignment_6_2");
			builder.put(grammarAccess.getModelAccess().getRefereesAssignment_6_3_1(), "rule__Model__RefereesAssignment_6_3_1");
			builder.put(grammarAccess.getModelAccess().getTimestampAssignment_7_1(), "rule__Model__TimestampAssignment_7_1");
			builder.put(grammarAccess.getNamedElementAccess().getNameAssignment_2(), "rule__NamedElement__NameAssignment_2");
			builder.put(grammarAccess.getNamedElementAccess().getRefereesAssignment_4_2(), "rule__NamedElement__RefereesAssignment_4_2");
			builder.put(grammarAccess.getNamedElementAccess().getRefereesAssignment_4_3_1(), "rule__NamedElement__RefereesAssignment_4_3_1");
			builder.put(grammarAccess.getNamedElementAccess().getTimestampAssignment_5_1(), "rule__NamedElement__TimestampAssignment_5_1");
			builder.put(grammarAccess.getPackageAccess().getNameAssignment_2(), "rule__Package__NameAssignment_2");
			builder.put(grammarAccess.getPackageAccess().getSubFragmentsAssignment_4_2(), "rule__Package__SubFragmentsAssignment_4_2");
			builder.put(grammarAccess.getPackageAccess().getSubFragmentsAssignment_4_3_1(), "rule__Package__SubFragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getPackageAccess().getNamedelementsDefinedAssignment_5_2(), "rule__Package__NamedelementsDefinedAssignment_5_2");
			builder.put(grammarAccess.getPackageAccess().getNamedelementsDefinedAssignment_5_3_1(), "rule__Package__NamedelementsDefinedAssignment_5_3_1");
			builder.put(grammarAccess.getPackageAccess().getNamedelementsUsedAssignment_6_2(), "rule__Package__NamedelementsUsedAssignment_6_2");
			builder.put(grammarAccess.getPackageAccess().getNamedelementsUsedAssignment_6_3_1(), "rule__Package__NamedelementsUsedAssignment_6_3_1");
			builder.put(grammarAccess.getPackageAccess().getClassesAssignment_7_2(), "rule__Package__ClassesAssignment_7_2");
			builder.put(grammarAccess.getPackageAccess().getClassesAssignment_7_3_1(), "rule__Package__ClassesAssignment_7_3_1");
			builder.put(grammarAccess.getPackageAccess().getRefereesAssignment_8_2(), "rule__Package__RefereesAssignment_8_2");
			builder.put(grammarAccess.getPackageAccess().getRefereesAssignment_8_3_1(), "rule__Package__RefereesAssignment_8_3_1");
			builder.put(grammarAccess.getPackageAccess().getTimestampAssignment_9_1(), "rule__Package__TimestampAssignment_9_1");
			builder.put(grammarAccess.getClasseAccess().getNameAssignment_2(), "rule__Classe__NameAssignment_2");
			builder.put(grammarAccess.getClasseAccess().getSubFragmentsAssignment_4_2(), "rule__Classe__SubFragmentsAssignment_4_2");
			builder.put(grammarAccess.getClasseAccess().getSubFragmentsAssignment_4_3_1(), "rule__Classe__SubFragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getClasseAccess().getNamedelementsDefinedAssignment_5_2(), "rule__Classe__NamedelementsDefinedAssignment_5_2");
			builder.put(grammarAccess.getClasseAccess().getNamedelementsDefinedAssignment_5_3_1(), "rule__Classe__NamedelementsDefinedAssignment_5_3_1");
			builder.put(grammarAccess.getClasseAccess().getNamedelementsUsedAssignment_6_2(), "rule__Classe__NamedelementsUsedAssignment_6_2");
			builder.put(grammarAccess.getClasseAccess().getNamedelementsUsedAssignment_6_3_1(), "rule__Classe__NamedelementsUsedAssignment_6_3_1");
			builder.put(grammarAccess.getClasseAccess().getStructuralfeaturesAssignment_7_2(), "rule__Classe__StructuralfeaturesAssignment_7_2");
			builder.put(grammarAccess.getClasseAccess().getStructuralfeaturesAssignment_7_3_1(), "rule__Classe__StructuralfeaturesAssignment_7_3_1");
			builder.put(grammarAccess.getClasseAccess().getRefereesAssignment_8_2(), "rule__Classe__RefereesAssignment_8_2");
			builder.put(grammarAccess.getClasseAccess().getRefereesAssignment_8_3_1(), "rule__Classe__RefereesAssignment_8_3_1");
			builder.put(grammarAccess.getClasseAccess().getTimestampAssignment_9_1(), "rule__Classe__TimestampAssignment_9_1");
			builder.put(grammarAccess.getStructuralFeatureAccess().getNameAssignment_2(), "rule__StructuralFeature__NameAssignment_2");
			builder.put(grammarAccess.getStructuralFeatureAccess().getSubFragmentsAssignment_4_2(), "rule__StructuralFeature__SubFragmentsAssignment_4_2");
			builder.put(grammarAccess.getStructuralFeatureAccess().getSubFragmentsAssignment_4_3_1(), "rule__StructuralFeature__SubFragmentsAssignment_4_3_1");
			builder.put(grammarAccess.getStructuralFeatureAccess().getNamedelementsDefinedAssignment_5_2(), "rule__StructuralFeature__NamedelementsDefinedAssignment_5_2");
			builder.put(grammarAccess.getStructuralFeatureAccess().getNamedelementsDefinedAssignment_5_3_1(), "rule__StructuralFeature__NamedelementsDefinedAssignment_5_3_1");
			builder.put(grammarAccess.getStructuralFeatureAccess().getNamedelementsUsedAssignment_6_2(), "rule__StructuralFeature__NamedelementsUsedAssignment_6_2");
			builder.put(grammarAccess.getStructuralFeatureAccess().getNamedelementsUsedAssignment_6_3_1(), "rule__StructuralFeature__NamedelementsUsedAssignment_6_3_1");
			builder.put(grammarAccess.getStructuralFeatureAccess().getRefereesAssignment_7_2(), "rule__StructuralFeature__RefereesAssignment_7_2");
			builder.put(grammarAccess.getStructuralFeatureAccess().getRefereesAssignment_7_3_1(), "rule__StructuralFeature__RefereesAssignment_7_3_1");
			builder.put(grammarAccess.getStructuralFeatureAccess().getTimestampAssignment_8_1(), "rule__StructuralFeature__TimestampAssignment_8_1");
			builder.put(grammarAccess.getDomainType_ImplAccess().getNameAssignment_2(), "rule__DomainType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getEngineeringType_ImplAccess().getNameAssignment_2(), "rule__EngineeringType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getRefereeAccess().getNameAssignment_2(), "rule__Referee__NameAssignment_2");
			builder.put(grammarAccess.getEvidence_ImplAccess().getNameAssignment_2(), "rule__Evidence_Impl__NameAssignment_2");
			builder.put(grammarAccess.getEvidence_ImplAccess().getImpactedElementsAssignment_4_2(), "rule__Evidence_Impl__ImpactedElementsAssignment_4_2");
			builder.put(grammarAccess.getEvidence_ImplAccess().getImpactedElementsAssignment_4_3_1(), "rule__Evidence_Impl__ImpactedElementsAssignment_4_3_1");
			builder.put(grammarAccess.getEvidence_ImplAccess().getRefereesAssignment_5_2(), "rule__Evidence_Impl__RefereesAssignment_5_2");
			builder.put(grammarAccess.getEvidence_ImplAccess().getRefereesAssignment_5_3_1(), "rule__Evidence_Impl__RefereesAssignment_5_3_1");
			builder.put(grammarAccess.getEvidence_ImplAccess().getTimestampAssignment_6_1(), "rule__Evidence_Impl__TimestampAssignment_6_1");
			builder.put(grammarAccess.getRuleEvidenceAccess().getNameAssignment_2(), "rule__RuleEvidence__NameAssignment_2");
			builder.put(grammarAccess.getRuleEvidenceAccess().getRuleAssignment_4_1(), "rule__RuleEvidence__RuleAssignment_4_1");
			builder.put(grammarAccess.getRuleEvidenceAccess().getExecutionDateAssignment_5_1(), "rule__RuleEvidence__ExecutionDateAssignment_5_1");
			builder.put(grammarAccess.getRuleEvidenceAccess().getImpactedElementsAssignment_6_2(), "rule__RuleEvidence__ImpactedElementsAssignment_6_2");
			builder.put(grammarAccess.getRuleEvidenceAccess().getImpactedElementsAssignment_6_3_1(), "rule__RuleEvidence__ImpactedElementsAssignment_6_3_1");
			builder.put(grammarAccess.getRuleEvidenceAccess().getRefereesAssignment_7_2(), "rule__RuleEvidence__RefereesAssignment_7_2");
			builder.put(grammarAccess.getRuleEvidenceAccess().getRefereesAssignment_7_3_1(), "rule__RuleEvidence__RefereesAssignment_7_3_1");
			builder.put(grammarAccess.getRuleEvidenceAccess().getTimestampAssignment_8_1(), "rule__RuleEvidence__TimestampAssignment_8_1");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getNameAssignment_2(), "rule__AnnotationEvidence__NameAssignment_2");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getContentAssignment_4_1(), "rule__AnnotationEvidence__ContentAssignment_4_1");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getImpactedElementsAssignment_5_2(), "rule__AnnotationEvidence__ImpactedElementsAssignment_5_2");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getImpactedElementsAssignment_5_3_1(), "rule__AnnotationEvidence__ImpactedElementsAssignment_5_3_1");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getRefereesAssignment_6_2(), "rule__AnnotationEvidence__RefereesAssignment_6_2");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getRefereesAssignment_6_3_1(), "rule__AnnotationEvidence__RefereesAssignment_6_3_1");
			builder.put(grammarAccess.getAnnotationEvidenceAccess().getTimestampAssignment_7_1(), "rule__AnnotationEvidence__TimestampAssignment_7_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getNameAssignment_2(), "rule__AIEvidence__NameAssignment_2");
			builder.put(grammarAccess.getAIEvidenceAccess().getAlgorithmUsedAssignment_4_1(), "rule__AIEvidence__AlgorithmUsedAssignment_4_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getParametersAssignment_5_2(), "rule__AIEvidence__ParametersAssignment_5_2");
			builder.put(grammarAccess.getAIEvidenceAccess().getParametersAssignment_5_3_1(), "rule__AIEvidence__ParametersAssignment_5_3_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getExecutionDateAssignment_6_1(), "rule__AIEvidence__ExecutionDateAssignment_6_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getPrecisionAssignment_7_1(), "rule__AIEvidence__PrecisionAssignment_7_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getRecallAssignment_7_2(), "rule__AIEvidence__RecallAssignment_7_2");
			builder.put(grammarAccess.getAIEvidenceAccess().getImpactedElementsAssignment_8_2(), "rule__AIEvidence__ImpactedElementsAssignment_8_2");
			builder.put(grammarAccess.getAIEvidenceAccess().getImpactedElementsAssignment_8_3_1(), "rule__AIEvidence__ImpactedElementsAssignment_8_3_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getRefereesAssignment_9_2(), "rule__AIEvidence__RefereesAssignment_9_2");
			builder.put(grammarAccess.getAIEvidenceAccess().getRefereesAssignment_9_3_1(), "rule__AIEvidence__RefereesAssignment_9_3_1");
			builder.put(grammarAccess.getAIEvidenceAccess().getTimestampAssignment_10_1(), "rule__AIEvidence__TimestampAssignment_10_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TraceaGrammarAccess grammarAccess;

	@Override
	protected InternalTraceaParser createParser() {
		InternalTraceaParser result = new InternalTraceaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TraceaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TraceaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
