/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TraceaUiModule extends AbstractTraceaUiModule {

	public TraceaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
