/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTraceaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tracea.ecore"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tracea.ecore.core"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tracea.ecore.granularity"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tracea.ecore.relationtyping"));
		return result;
	}
}
