/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uoc.som.tracea.ui.internal.TraceaActivator;

public class TraceaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TraceaActivator.getInstance().getInjector("uoc.som.tracea.Tracea");
	}

}
