/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uoc.som.tracea.ui.internal.TraceaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TraceaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TraceaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TraceaActivator activator = TraceaActivator.getInstance();
		return activator != null ? activator.getInjector(TraceaActivator.UOC_SOM_TRACEA_TRACEA) : null;
	}

}
