/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTraceaScopeProvider extends DelegatingScopeProvider {
}
