/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TraceaStandaloneSetup extends TraceaStandaloneSetupGenerated {

	public static void doSetup() {
		new TraceaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
