/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TraceaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uoc/som/tracea/parser/antlr/internal/InternalTracea.tokens");
	}
}
