/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uoc.som.tracea.services.TraceaGrammarAccess;

@SuppressWarnings("all")
public class TraceaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TraceaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Trace_RightCurlyBracketKeyword_6_1_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TraceaGrammarAccess) access;
		match_Trace_RightCurlyBracketKeyword_6_1_1_q = new TokenAlias(false, true, grammarAccess.getTraceAccess().getRightCurlyBracketKeyword_6_1_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Trace_RightCurlyBracketKeyword_6_1_1_q.equals(syntax))
				emit_Trace_RightCurlyBracketKeyword_6_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '}'?
	 *
	 * This ambiguous syntax occurs at:
	 *     evidences+=[Evidence|EString] '}' (ambiguity) 'referees' '(' referees+=[Referee|EString]
	 *     evidences+=[Evidence|EString] '}' (ambiguity) 'timestamp' timestamp=EString
	 *     evidences+=[Evidence|EString] '}' (ambiguity) 'tracelinks' '{' tracelinks+=TraceLink
	 *     evidences+=[Evidence|EString] '}' (ambiguity) '}' (rule end)
	 *     name=EString '{' (ambiguity) 'referees' '(' referees+=[Referee|EString]
	 *     name=EString '{' (ambiguity) 'timestamp' timestamp=EString
	 *     name=EString '{' (ambiguity) 'tracelinks' '{' tracelinks+=TraceLink
	 *     name=EString '{' (ambiguity) '}' (rule end)
	 *     relationshiptype=[RelationshipType|EString] (ambiguity) 'referees' '(' referees+=[Referee|EString]
	 *     relationshiptype=[RelationshipType|EString] (ambiguity) 'timestamp' timestamp=EString
	 *     relationshiptype=[RelationshipType|EString] (ambiguity) 'tracelinks' '{' tracelinks+=TraceLink
	 *     relationshiptype=[RelationshipType|EString] (ambiguity) '}' (rule end)
	 */
	protected void emit_Trace_RightCurlyBracketKeyword_6_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
