/*
 * generated by Xtext 2.21.0
 */
package uoc.som.tracea.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class TraceaScopeProvider extends AbstractTraceaScopeProvider {

}
